plugins:
  digest_report2_enabled:
    default: true
    client: true

  digest_report2_endpoint_url:
    default: ""
    client: false

  digest_report2_open_tracking_enabled:
    default: false
    client: true

  digest_report2_pixel_force_discourse_domain:
    default: false
    client: false
    type: bool    

  digest_report2_message_id_swap_enabled:
    default: false
    client: true

  # Optional: if set, this host is used for BOTH:
  #  - pixel domain
  #  - Message-ID target domain
  # If blank: use domain from the first found <a href="http(s)://..."> link in the email.
  digest_report2_target_domain_override:
    default: ""
    client: true
